# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)
steps:
- script: echo Job1 - Hello, world, changed!
  displayName: 'Run a one-line script'

- script: echo "This is a secind trask"
  displayName: "Welcome to Azure Pipeline"
