

trigger:
- master

pool:
  name: news
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)
stages:
- stage: first
  jobs:
  - job: build
    steps:
    - script: echo Job1 - Hello, world, changed!
      displayName: 'Run a one-line script'

    - script: echo "This is a secind trask"
      displayName: "Welcome to Azure Pipeline"
   
    - bash:  echo $(ENV)
    - bash: sudo apt-get update -y
    - bash: sudo apt-get install docker.io -y
    - bash: sudo usermod -aG docker AzDevOps
    - bash: sudo chmod 666 /var/run/docker.sock
    - bash: sudo systemctl restart docker 
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
             **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory) 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'nippy/mycustom-image'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
 


  - task: AzureWebApp@1
    inputs:
     azureSubscription: 'Free Trial(1)(75a2b295-b2c9-403a-b4a9-7fce370cc20e)'
     appType: 'webAppLinux'
     appName: 'newsa'
     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
     runtimeStack: 'TOMCAT|9.0-java17'